### ISSUE TITLE
Guild default channels are no longer a thing

### ISSUE THREAD

**Issue by ioistired** [ErikBoesen/tokenwarn#2]
What channel should the bot send to? All channels? Perhaps a random channel that everyone can access?

**Comment by ioistired** [comment]
The bot could also just DM the bot owner and leave it at that. This will be less likely to scare people on random servers. That would also mean that servers such as Discord Bot List would not be notified, however.

**Comment by ErikBoesen** [comment]
DMing might be a superior option.

**Comment by ioistired** [comment]
Fixed by #7
